package com.example.springdatajpatips.exception;

import com.fasterxml.jackson.annotation.JsonFormat;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum CustomError {
	
	INTERNAL_SERVER_ERROR(500, "INTERNAL_SERVER_ERROR"),
	SESSION_EXPIRED(419, "SESSION_EXPIRED"),
	
	INVALID_COMPANY_NAME(1001, "INVALID_COMPANY_NAME"),
	INVALID_PARENT_COMPANY_NAME(1002, "INVALID_PARENT_COMPANY_NAME"),
	INVALID_COMPANY_GROUP_ID(1003, "INVALID_COMPANY_GROUP_ID"),
	INVALID_TERRITORY(1004, "INVALID_TERRITORY"),
	INVALID_CITY(1005, "INVALID_CITY"),
	INVALID_COUNTRY(1006, "INVALID_COUNTRY"),
	INVALID_SUBSCRIPTION_TYPE(1007, "INVALID_SUBSCRIPTION_TYPE"),
	INVALID_SUBSCRIPTION_PERIOD(1008, "INVALID_SUBSCRIPTION_PERIOD"),
	INVALID_SUBSCRIPTION_PERIOD_TYPE(1009, "INVALID_SUBSCRIPTION_PERIOD_TYPE"),
	INVALID_SUBSCRIPTION_START_DATE(1010, "INVALID_SUBSCRIPTION_START_DATE"),
	INVALID_SUBSCRIPTION_END_DATE(1011, "INVALID_SUBSCRIPTION_END_DATE"),
	INVALID_LICENSE_COUNT(1012, "INVALID_LICENSE_COUNT"),
	INVALID_LICENSES(1013, "INVALID_LICENSES"),
	DUPLICATE_COMPANY_NAME(1014, "DUPLICATE_COMPANY_NAME"),
	INVALID_COMPANY_ID(1015, "INVALID_COMPANY_ID"),
	COMPANY_NOT_FOUND(1016, "COMPANY_NOT_FOUND"),

	INVALID_ID_LIST(1043, "INVALID_ID_LIST"),
	INVALID_PRODUCT_CONTENT_ID(1044, "INVALID_PRODUCT_CONTENT_ID"),
	MALFORMED_JSON_EXCEPTION(1045,"MALFORMED_JSON_EXCEPTION"),

	LICENSES_CANNOT_BE_NULL_OR_EMPTY(1059,"LICENSES_CANNOT_BE_NULL_OR_EMPTY"),
	INVALID_PRODUCT_CONTENT_PURCHASE_COUNT(1060,"PRODUCT_CONTENT_PURCHASE_COUNT_MUST_BE_GREATER_THAN_ZERO"),
	INVALID_COMPANY_PROFILE(1061,"INVALID_COMPANY_PROFILE"),
	INVALID_SUBSCRIPTION_DETAILS(1062,"INVALID_SUBSCRIPTION_DETAILS"),
	INVALID_COMPANY_LOCK_VALUE(1063,"INVALID_COMPANY_LOCK_VALUE"),
	INVALID_SEND_EMAIL_TO_TERRITORY_ADMIN_VALUE(1064,"INVALID_SEND_EMAIL_TO_TERRITORY_ADMIN_VALUE"),
	INVALID_COMPANY_DOMAIN(1065,"INVALID_COMPANY_DOMAIN"),


	;
	
	private String errorKey;
	private int errorCode;
	
	private CustomError(int errorCode, String errorKey) {
		this.errorCode = errorCode;
		this.errorKey = errorKey;
	}

	public String getErrorKey() {
		return errorKey;
	}

	public void setErrorKey(String errorKey) {
		this.errorKey = errorKey;
	}

	public int getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(int errorCode) {
		this.errorCode = errorCode;
	}
}
